spring:
  application:

  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create


  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: '{cipher}AQB+RBN78lIThgLY9W8Rm2KqjlvxgWjOTzezaSJ+MoRnCW7XFUHGq66tzSdsywPydYQo8mLWWwhKV4OltLduoyT66PpJP4yMEpX1UOt/akunmJExglF6GNu+mSOG59B6JRdcyr0nT/YVx86MtuOlE3E8ldhdJxuTagPc7t2VXjVYkmS+EXRuN1GbksO6wBms+MTK3b9OGxdMSUNXZqWARX9vl8RFsg/Aoqwd9zo65L6r2TbmJw9PgDOm/9RYnMGlpog1Acf6ZoWJt35NfADTyPAq02G3Aq7lJWXWSM/zGKsPXs8hw/16fJOOoWr+mknsE9vCIKvw84t+UhZDTodIETEz6RqhO59sopjbZxob8Dzri0MmD6m5BKxfjySaB5sgdx0='

server:
  port: 8083

yoke:
  notify:
    url: http://YOKE-NOTIFY/event
